### PR TITLE
Sharpen parameter "default" property description

### PR DESCRIPTION
**Pull request by earth2marsh**
As discussed on IRC

### CODE REVIEW

**Comment by webron** [comment]
Thanks @earth2marsh!

The definition of `default` is repeated several times in the spec. Can you please update all descriptions?

**Comment by earth2marsh** [comment]
@webron with pleasure. AFAICT, that means `itemsDefault` and `headerDefault`? Anything else?

**Comment by webron** [comment]
Those two, yeah.

**Comment by earth2marsh** [comment]
LMK if I missed anything!

**Comment by webron** [comment]
Thanks a bunch!

**Comment by tadhgpearson** [comment]
Thanks for this clarification.
What now replaces the 'other' value of default, where it's also used as the default pre-populated value for a field? I'm particularly thinking of Smartdocs here @earth2marsh  ;)

**Pull request merged**
