### PR TITLE
Fixes support of empty schemas.

### LINKED ISSUE #452: Using empty schema object does not work anymore
Since this change,

https://github.com/swagger-api/swagger-spec/commit/9db746f2aab8b8b29c1765e61dc57ee4dd8c2a05

It's not possible anymore to specify an empty schema object in a response.

```json
{ }
```

I believe this is because of the "oneOf" operator:

```json
"oneOf": [
            {
              "$ref": "#/definitions/schema"
            },
            {
              "$ref": "#/definitions/fileSchema"
            }
          ]
```

since { } matches both schemas ... it fails validation.

A simple fix for this I think is to make the "type" field required for  "#/definitions/fileSchema"

### PR DESCRIPTION
**Pull request by IvanGoncharov**
@webron It pretty simple one line fix, but it significantly blocks me.
Fixes #452

### CODE REVIEW

**Comment by webron** [comment]
Thanks, and sorry it slipped through.

**Comment by webron** [comment]
@whitlockjc, @mohsen1 - when you get a chance, please update the schema to help resolve the issue with the editor.

**Comment by IvanGoncharov** [comment]
@webron Thanks

**Comment by mohsen1** [comment]
Published this change at swagger-schema-official@2.0.0-bab6bed

**Pull request merged**
