### PR TITLE
Add link SwaggerAssertions tool

### PR DESCRIPTION
**Pull request by Maks3w**
SwaggerAssertions provides test assertions for validate your API requests and responses matches with your Swagger definition.

### CODE REVIEW

**Comment by Maks3w** [comment]
Fixed, thank you @webron

**Comment by webron** [comment]
Great, thanks for adding!

**Comment by webron** [comment]
@Maks3w  - can I get your email please? Looking to contact library developers directly. You can send it to me by email if you prefer, email in profile.

**Comment by Maks3w** [comment]
Mail is in git commit

**Pull request merged**
