### PR TITLE
allowed response type of `file`

### PR DESCRIPTION
**Pull request by nickretallack**
Not sure if this is the best way to do it, but we should do something to support what the documentation says we do.  Comments welcome.

Not sure how to "test" this or try it out in swagger-editor.

### CODE REVIEW

**Comment by webron** [comment]
If you fix it (the `responseSchema` is defined inside `schema` by mistake) and resubmit it against the 2.0_fixes branches, I'd be more than happy to merge it.

**Comment by webron** [comment]
Please note that I just pushed a few changes to the schema object in that branch, so make sure to pull those.

**Comment by ePaul** [comment]
If I understand right, when using `"type": "file"`, there is no much point in including anything else in this schema definition. So maybe something like

    "responseSchema": {
        "anyOf": [ {
                "$ref": "#/definitions/schema"
             }, {
                "type": "object"
                "properties": {
                    "type": {
                        "type": "string",
                        "enum": [ "file" ]
                    }
                }
            }
        ]
    }

would be shorter, easier maintainable and allow less nonsense? (I'm not an expert on JSON schema, I find the spec unreadable, and have no tools here to try if this works. I hope the intention is clear.)

**Comment by webron** [comment]
Thanks, but due to code drift, had to implement it differently.

**Pull request closed without merging**
