### PR TITLE
Added swagger2markup to tools list.

### PR DESCRIPTION
**Pull request by RobWin**
Added swagger2markup to the list of Community-Driven Language Integrations (Java).

### CODE REVIEW

**Comment by webron** [comment]
Shouldn't it actually go to this section - https://github.com/swagger-api/swagger-spec#community-driven-tools?

**Comment by RobWin** [comment]
I think it can only be used with Java.
And other API tool are there as well.

**Comment by RobWin** [comment]
Do I have to change it?

**Comment by webron** [comment]
Sorry, been traveling. I'll review it soon.

**Comment by RobWin** [comment]
NP :-)

**Comment by RobWin** [comment]
Anything New?

**Comment by RobWin** [comment]
Thx

**Comment by webron** [comment]
Apologies for the delay, and thank you for submitting the PR!

**Pull request merged**
